// frontend/src/components/Footer/Footer.tsx
import React, { HTMLAttributes } from "react";
import concatClasses from "../../functions/concatClasses";
import classes from "./Footer.module.scss";

export type FooterProps = { text: string } & HTMLAttributes<HTMLElement>;

export const Footer = ({ className, text, ...props }: FooterProps) => {
	return (
		<footer className={concatClasses(classes["footer"], className)} {...props}>
			<p>
				{text} — {new Date().getFullYear()}
			</p>
		</footer>
	);
};

// frontend/src/components/Footer.svelte
<script lang="ts">
	import concatClasses from "../functions/concatClasses";

	export let text: string;
	export let className = "";
</script>

<footer class={concatClasses("footer", className)}>
	<p>
		{text} — {new Date().getFullYear()}
	</p>
</footer>

<style lang="scss">
	@import "../styles/includes.scss";

	.footer {
		color: $text;

		text-align: center;

		font-size: 14px;

		margin-block-start: 2rem;
	}
</style>
