// frontend/src/components/ContactInfo.svelte
<script lang="ts">
	import concatClasses from "../functions/concatClasses";
	import Anchor from "../Anchor.svelte";
	import ChildWithPrefix from "../ChildWithPrefix.svelte";

	export let className = "";
	export let contacts: [
		{
			text: string;
			type: "discord" | "email" | "phone";
		}
	];
</script>

<address
	class={concatClasses([["contact-info"], true], [className, className])}
>
	{#each contacts as contact}
		<ChildWithPrefix prefix={contact.type}>
			{#if contact.type === "discord"}
				<p tabIndex={0}>{contact.text}</p>
			{:else if contact.type === "email"}
				<Anchor href={`mailto:${contact.text}`}>{contact.text}</Anchor>
			{:else if contact.type === "phone"}
				<Anchor href={`tel:${contact.text.split(/[\s,-]+/g).join("")}`}>
					{contact.text}
				</Anchor>
			{/if}
		</ChildWithPrefix>
	{/each}
</address>

<style lang="scss">
	@import "../styles/includes";

	.contact-info {
		margin-block-start: 0.5em;
		display: inline-flex;
		flex-direction: column;
		justify-content: space-evenly;
		gap: 0.5rem;
	}
</style>

// src/components/ContactInfo/ContactInfo.tsx
import React, { HTMLAttributes } from "react";
import concatClasses from "../../functions/concatClasses";
import { TContactInfo } from "../../types";
import { Anchor } from "../Anchor";
import { ChildWithPrefix } from "../ChildWithPrefix";
import classes from "./ContactInfo.module.scss";

export type ContactInfoProps = TContactInfo & HTMLAttributes<HTMLElement>;

export const ContactInfo = ({
	className,
	discord,
	email,
	phonenumber,
}: ContactInfoProps) => {
	return (
		<address
			className={concatClasses(
				[classes["contact-info"], true],
				[className, className]
			)}
		>
			<ChildWithPrefix prefix="discord">
				<p tabIndex={0}>{discord}</p>
			</ChildWithPrefix>
			<ChildWithPrefix prefix="email">
				<Anchor href={`mailto:${email}`}>{email}</Anchor>
			</ChildWithPrefix>
			<ChildWithPrefix prefix="phone">
				<Anchor href={`tel:${phonenumber.split(/[\s,-]+/g).join("")}`}>
					{phonenumber}
				</Anchor>
			</ChildWithPrefix>
		</address>
	);
};
