// frontend/src/components/Header/Header.tsx
import React, { HTMLAttributes } from "react";
import concatClasses from "../../functions/concatClasses";
import { getStrapiURL } from "../../utils/api";
import { getStrapiMedia } from "../../utils/media";
import { Heading } from "../Heading";
import { Image } from "../Image";
import classes from "./Header.module.scss";

type HeaderProps = {
	headshot: {
		formats: {
			medium: {
				url: string;
				width: number;
			};
			small: {
				url: string;
				width: number;
			};
			thumbnail: {
				url: string;
				width: number;
			};
		};
		url: string;
		width: number;
	};
	title: string;
} & HTMLAttributes<HTMLElement>;

export const Header = ({
	className,
	headshot,
	title,
}: HeaderProps): JSX.Element => {
	const { formats, url, width: orgWidth } = headshot;
	return (
		<header
			className={concatClasses(classes["header"], [className, className])}
		>
			<Image
				alt={title}
				className={classes["image"]}
				src={url}
				srcSet={Object.values(formats)
					.map(({ url, width }) => `${getStrapiMedia(url)} ${width}w`)
					.join(", ")}
				sizes={`${Object.values(formats)
					.sort((a, b) => a.width - b.width)
					.map(({ width }, i, arr) => {
						const nextWidth = arr[i + 1]?.width || orgWidth;
						return `(max-width: ${nextWidth}px) ${width}px`;
					})
					.join(", ")}, ${orgWidth}px`}
			/>
			<Heading type="h1" className={classes["title"]}>
				{title}
			</Heading>
		</header>
	);
};

// frontend/src/lib/components/Header.svelte
<script lang="ts">
	import { getStrapiMedia } from '$lib/utils/media';

	import concatClasses from '../functions/concatClasses';
	import Image from './Image.svelte';

	export let headshot: {
		formats: {
			medium: {
				url: string;
				width: number;
			};
			small: {
				url: string;
				width: number;
			};
			thumbnail: {
				url: string;
				width: number;
			};
		};
		url: string;
		width: number;
	};
	export let title: string;
	export let className = '';

	let { formats, url, width: orgWidth } = headshot;
</script>

<header class={concatClasses('header', [className, className])}>
	<!-- <Image
		alt={title}
		className={'image'}
		src={url}
		srcSet={Object.values(formats)
			.map(({ url, width }) => `${getStrapiMedia(url)} ${width}w`)
			.join(', ')}
		sizes={`${Object.values(formats)
			.sort((a, b) => a.width - b.width)
			.map(({ width }, i, arr) => {
				const nextWidth = arr[i + 1]?.width || orgWidth;
				return `(max-width: ${nextWidth}px) ${width}px`;
			})
			.join(', ')}, ${orgWidth}px`}
	/> -->
	<h1 class={'title'}>
		{title}
	</h1>
</header>

<style lang="scss">
	@import '../../styles/includes';

	.header {
		display: grid;
		gap: 0 0.5em;
		grid-template-columns: 1fr auto;
		grid-template-areas: 'title image';

		margin-bottom: 1rem;
	}

	.image {
		grid-area: image;

		align-self: center;
		object-fit: contain;

		max-width: 128px;
		max-height: 128px;
		width: 100%;
		height: 100%;
	}

	.title {
		grid-area: title;

		margin: 0;

		align-self: center;

		word-break: normal;
	}
</style>
