// src/components/Image/Image.tsx
import React, { ImgHTMLAttributes } from "react";
import concatClasses from "../../functions/concatClasses";

type ImageProps = {
	alt: string;
} & ImgHTMLAttributes<HTMLElement>;

export const Image = ({ alt, className, src, ...props }: ImageProps) => {
	return (
		<img
			alt={alt}
			src={src}
			height={128}
			width={128}
			className={concatClasses([className, className])}
			{...props}
		/>
	);
};

// frontend/src/lib/components/Image.svelte
<script lang="ts">
	import concatClasses from "../functions/concatClasses";
	import { getStrapiMedia } from "../utils/media";

	export let src: string;
	export let alt: string;
	export let className = "";
</script>

<img
	{alt}
	src={getStrapiMedia(src)}
	class={concatClasses([className, className])}
	{...$$props}
/>
